name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: setup minimum version Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - uses: actions/checkout@v1
    - name: prepare manifest.json with a revision number
      run: |
        cp manifest.json manifest.json.bak
        version=$(cat manifest.json.bak | jq -r ".version" | sed -r -e "s/$/.$(git log --oneline | wc -l)/")
        cat manifest.json.bak | jq ".version |= \"$version\"" > manifest.json
    - name: build xpi
      run: make
    - uses: actions/upload-artifact@master
      with:
        name: copy-selected-tabs-to-clipboard.xpi
        path: copy-selected-tabs-to-clipboard.xpi
